name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Cambiamos 'lowlighter/metrics@latest' por el fork de la comunidad que tiene los artefactos actualizados v4
      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Madrid
          base: header, activity, community, repositories, metadata
          plugin_repositories: yes
          plugin_repositories_starred: 10
          plugin_repositories_order: starred
