name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Madrid
          
          # 1. Dejamos la base original para que vuelvan a salir los gráficos de Issues y PRs
          base: header, activity, community, repositories, metadata
          
          # 2. El TRUCO: Apagamos explícitamente el plugin de lenguajes de 'metrics' 
          # para que no te duplique la barra que ya tienes en Vercel
          plugin_languages: no
          
          # 3. Tus repositorios destacados como los tenías antes
          plugin_repositories: yes
          plugin_repositories_starred: 10
          plugin_repositories_order: starred
