name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Madrid
          
          # 1. Filtramos la BASE para dejar solo la info global útil y quitar los lenguajes (metadata)
          base: header, activity, community, repositories
          
          # 2. Desactivamos explícitamente el desglose de líneas de código y lenguajes en la base
          base_indepth: no
          base_hireable: no
          
          # 3. Configuramos tus repositorios destacados (lo que ya tenías)
          plugin_repositories: yes
          plugin_repositories_starred: 10
          plugin_repositories_order: starred

          # Nota: Al no añadir "plugin_languages: yes" ni "metadata" en la base, 
          # la barra de Shell/Rust/WGSL desaparecerá de esta imagen, dejando el protagonismo a tu tarjeta de Vercel.
